zuul:
  ignoredServices: '*'
  routes:
    billing: /api/billing/**
endpoints:
  actuator:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:12345/eureka
server:
  port: 54321